export const title = `TRẢI NGHIỆM HỌC TẠI TRUNG TÂM LUYỆN THI KHAI TÂM`;
export const body = `
Trung tâm Luyện thi Khai Tâm được hình thành nên từ một ý tưởng nhen nhóm của cô giáo viên non trẻ, mang theo nhiệt huyết và ước muốn giúp sức cho các em hướng đến giấc mơ tương lai của mình. Khai Tâm được xây dựng bởi cái “Tâm” của nghề giáo, giảng dạy và giúp “Khai” sáng tiềm năng 
<br><br>Khai Tâm mong muốn mang đến trải nghiệm học tập chất lượng nhất và thoải mái nhất cho học sinh. Mỗi lớp học chỉ giới hạn tối đa 25 học sinh, không cố gắng nhồi nhét quá nhiều học sinh, đảm bảo chất lượng buổi học. Với số lượng học sinh ít, giáo viên có thể quan tâm đến từng em, đánh giá trình độ năng lực riêng và định hướng giảng dạy phù hợp. Phòng học được trang bị đầy đủ tiện nghi, ánh sáng, bàn ghế, máy lạnh, máy chiếu, micro và loa.
<br><br>Chủ trương giảng dạy của Khai Tâm là tạo môi trường thân thiện, thoải mái cho các em, lấy học sinh làm trung tâm, phát triển tư duy dựa trên tương tác giữa thầy và trò. Học sinh sẽ được trải nghiệm học thử tất cả các môn tại Trung Tâm trong 2 tuần. Nếu các em cảm thấy môi trường học tập không phù hợp, Khai Tâm đảm bảo hoàn tiền 100% học phí. Học phí chỉ cần đóng theo từng khóa thay vì nhiều khóa như các Trung tâm khác, giúp cho quý phụ huynh chủ động hơn trong việc chi trả, bởi vì Khai Tâm hiểu có rất nhiều bạn có hoàn cảnh khó khăn ngoài kia cần phải chạm đến con đường tri thức!
<br><br>Học đi đôi với Hành, phản xạ nhanh nhạy rèn luyện qua các thử thách liên tục. Bên cạnh việc đào tạo vững chắc kiến thức từ căn bản đến nâng cao cho học sinh, Khai Tâm thường xuyên tổ chức các buổi lượng giá, thi thử cho học sinh. Đề thi được sưu tầm từ nhiều trường, nhiều giáo viên và các đề thi qua các năm. Cấu trúc đề sẽ được đổi mới liên tục dựa trên quy chế thi của Bộ Giáo dục.
<br><br>Chương trình học được lên kế hoạch rõ ràng cho từng cấp và các giai đoạn thi cử. Học sinh sẽ được nhân viên tại Trung tâm nhắc nhở thời gian ôn bài, làm bài tập cũng như ôn thi. Khai Tâm theo sát các em nhưng tuyệt nhiên không tạo nên không khí áp lực, bí bách cho các em. Ngoài ra, nhằm nâng cao trình độ các em học sinh yếu kém, Trung tâm Khai Tâm có tổ chức thêm các buổi tăng cường miễn phí cho các em. Mục đích giúp các em nắm vững kiến thức và có nhiều thời gian hơn trong việc ôn luyện.
<br><br>Hằng năm, những em đạt được thành tích tốt trong các kì thi sẽ được viết tên lên Bảng Vàng vinh danh và nhận được các phần thưởng khích lệ xứng đáng.
<br><br>“Không để ai lại phía sau trên con đường tri thức” – Khai Tâm luôn lấy tiêu chí đó làm kim chỉ Nam trong việc định hướng hoạt động của Trung Tâm. Chất lượng đến từ sự tinh giản và sự quan tâm ân cần của giáo viên đối với học sinh, chúng tôi luôn cố gắng xây dựng môi trường thân thiện và thoải mái nhất cho các em. Bên cạnh đó, những phần thưởng xứng đáng luôn là niềm động viên khích lệ cho các em trên con đường chinh phục của mình.
`;
export const footer = `Chào mừng các em đến với Khai Tâm!`;
